
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef __canfestival_master_H
#define __canfestival_master_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);
void canopen_send_sdo(uint16_t message_sdo[]);
void canopen_send_sdo2(uint16_t message_sdo[]);

/* Master node data struct */
extern CO_Data masterObjdict_Data;
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/

#endif // MASTER_H
